package org.louis.hometutor.domain;

import java.io.Serializable;
import java.util.Date;

public class BaseReturn implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_base_return.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.guid
     *
     * @return the value of t_export_base_return.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.guid
     *
     * @param guid the value for t_export_base_return.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.return_guid
     *
     * @return the value of t_export_base_return.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnGuid() {
        return returnGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.return_guid
     *
     * @param returnGuid the value for t_export_base_return.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnGuid(String returnGuid) {
        this.returnGuid = returnGuid == null ? null : returnGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.type
     *
     * @return the value of t_export_base_return.type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.type
     *
     * @param type the value for t_export_base_return.type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.return_status
     *
     * @return the value of t_export_base_return.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.return_status
     *
     * @param returnStatus the value for t_export_base_return.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnStatus(String returnStatus) {
        this.returnStatus = returnStatus == null ? null : returnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.return_time
     *
     * @return the value of t_export_base_return.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.return_time
     *
     * @param returnTime the value for t_export_base_return.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.return_info
     *
     * @return the value of t_export_base_return.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnInfo() {
        return returnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.return_info
     *
     * @param returnInfo the value for t_export_base_return.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnInfo(String returnInfo) {
        this.returnInfo = returnInfo == null ? null : returnInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.create_date
     *
     * @return the value of t_export_base_return.create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.create_date
     *
     * @param createDate the value for t_export_base_return.create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_base_return.enterprise_id
     *
     * @return the value of t_export_base_return.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_base_return.enterprise_id
     *
     * @param enterpriseId the value for t_export_base_return.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", guid=").append(guid);
        sb.append(", returnGuid=").append(returnGuid);
        sb.append(", type=").append(type);
        sb.append(", returnStatus=").append(returnStatus);
        sb.append(", returnTime=").append(returnTime);
        sb.append(", returnInfo=").append(returnInfo);
        sb.append(", createDate=").append(createDate);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append("]");
        return sb.toString();
    }
}