package org.louis.hometutor.domain;

import java.io.Serializable;
import java.util.Date;

public class Clearance implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String clearanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date orderAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderReturnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.order_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date orderCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.invt_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date invtAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.invt_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String invtAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String invtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.invt_create_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String invtCreateFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.invt_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date invtCreateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String payNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String payCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String payName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date payAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String payAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.pay_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String payReturnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date logisticsAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsReturnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.logistics_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.receipt_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String receiptStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.delivery_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String deliveryStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.entry_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String entryStowageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.out_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String outStowageStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.check_pass_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String checkPassStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.arrived_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date arrivedAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.leave_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date leaveAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.leave_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String leaveAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.arrived_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String arrivedAppStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.overtime_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String overtimeFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.refund_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String refundFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String createdByCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.log_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_clearance.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.clearance_no
     *
     * @return the value of t_export_clearance.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getClearanceNo() {
        return clearanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.clearance_no
     *
     * @param clearanceNo the value for t_export_clearance.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setClearanceNo(String clearanceNo) {
        this.clearanceNo = clearanceNo == null ? null : clearanceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_no
     *
     * @return the value of t_export_clearance.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_no
     *
     * @param orderNo the value for t_export_clearance.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_type
     *
     * @return the value of t_export_clearance.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_type
     *
     * @param orderType the value for t_export_clearance.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.ebc_code
     *
     * @return the value of t_export_clearance.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbcCode() {
        return ebcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.ebc_code
     *
     * @param ebcCode the value for t_export_clearance.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbcCode(String ebcCode) {
        this.ebcCode = ebcCode == null ? null : ebcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.ebc_name
     *
     * @return the value of t_export_clearance.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbcName() {
        return ebcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.ebc_name
     *
     * @param ebcName the value for t_export_clearance.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbcName(String ebcName) {
        this.ebcName = ebcName == null ? null : ebcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.ebp_code
     *
     * @return the value of t_export_clearance.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbpCode() {
        return ebpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.ebp_code
     *
     * @param ebpCode the value for t_export_clearance.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbpCode(String ebpCode) {
        this.ebpCode = ebpCode == null ? null : ebpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.ebp_name
     *
     * @return the value of t_export_clearance.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbpName() {
        return ebpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.ebp_name
     *
     * @param ebpName the value for t_export_clearance.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbpName(String ebpName) {
        this.ebpName = ebpName == null ? null : ebpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_app_time
     *
     * @return the value of t_export_clearance.order_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getOrderAppTime() {
        return orderAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_app_time
     *
     * @param orderAppTime the value for t_export_clearance.order_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderAppTime(Date orderAppTime) {
        this.orderAppTime = orderAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_app_status
     *
     * @return the value of t_export_clearance.order_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderAppStatus() {
        return orderAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_app_status
     *
     * @param orderAppStatus the value for t_export_clearance.order_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderAppStatus(String orderAppStatus) {
        this.orderAppStatus = orderAppStatus == null ? null : orderAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_return_status
     *
     * @return the value of t_export_clearance.order_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderReturnStatus() {
        return orderReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_return_status
     *
     * @param orderReturnStatus the value for t_export_clearance.order_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderReturnStatus(String orderReturnStatus) {
        this.orderReturnStatus = orderReturnStatus == null ? null : orderReturnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.order_create_date
     *
     * @return the value of t_export_clearance.order_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getOrderCreateDate() {
        return orderCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.order_create_date
     *
     * @param orderCreateDate the value for t_export_clearance.order_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderCreateDate(Date orderCreateDate) {
        this.orderCreateDate = orderCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.invt_app_time
     *
     * @return the value of t_export_clearance.invt_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getInvtAppTime() {
        return invtAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.invt_app_time
     *
     * @param invtAppTime the value for t_export_clearance.invt_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtAppTime(Date invtAppTime) {
        this.invtAppTime = invtAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.invt_app_status
     *
     * @return the value of t_export_clearance.invt_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInvtAppStatus() {
        return invtAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.invt_app_status
     *
     * @param invtAppStatus the value for t_export_clearance.invt_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtAppStatus(String invtAppStatus) {
        this.invtAppStatus = invtAppStatus == null ? null : invtAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.invt_no
     *
     * @return the value of t_export_clearance.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInvtNo() {
        return invtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.invt_no
     *
     * @param invtNo the value for t_export_clearance.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtNo(String invtNo) {
        this.invtNo = invtNo == null ? null : invtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.invt_create_flag
     *
     * @return the value of t_export_clearance.invt_create_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInvtCreateFlag() {
        return invtCreateFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.invt_create_flag
     *
     * @param invtCreateFlag the value for t_export_clearance.invt_create_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtCreateFlag(String invtCreateFlag) {
        this.invtCreateFlag = invtCreateFlag == null ? null : invtCreateFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.invt_create_date
     *
     * @return the value of t_export_clearance.invt_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getInvtCreateDate() {
        return invtCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.invt_create_date
     *
     * @param invtCreateDate the value for t_export_clearance.invt_create_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtCreateDate(Date invtCreateDate) {
        this.invtCreateDate = invtCreateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_no
     *
     * @return the value of t_export_clearance.pay_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPayNo() {
        return payNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_no
     *
     * @param payNo the value for t_export_clearance.pay_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayNo(String payNo) {
        this.payNo = payNo == null ? null : payNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_code
     *
     * @return the value of t_export_clearance.pay_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPayCode() {
        return payCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_code
     *
     * @param payCode the value for t_export_clearance.pay_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayCode(String payCode) {
        this.payCode = payCode == null ? null : payCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_name
     *
     * @return the value of t_export_clearance.pay_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPayName() {
        return payName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_name
     *
     * @param payName the value for t_export_clearance.pay_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayName(String payName) {
        this.payName = payName == null ? null : payName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_app_time
     *
     * @return the value of t_export_clearance.pay_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getPayAppTime() {
        return payAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_app_time
     *
     * @param payAppTime the value for t_export_clearance.pay_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayAppTime(Date payAppTime) {
        this.payAppTime = payAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_app_status
     *
     * @return the value of t_export_clearance.pay_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPayAppStatus() {
        return payAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_app_status
     *
     * @param payAppStatus the value for t_export_clearance.pay_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayAppStatus(String payAppStatus) {
        this.payAppStatus = payAppStatus == null ? null : payAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.pay_return_status
     *
     * @return the value of t_export_clearance.pay_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPayReturnStatus() {
        return payReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.pay_return_status
     *
     * @param payReturnStatus the value for t_export_clearance.pay_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPayReturnStatus(String payReturnStatus) {
        this.payReturnStatus = payReturnStatus == null ? null : payReturnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_no
     *
     * @return the value of t_export_clearance.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_no
     *
     * @param logisticsNo the value for t_export_clearance.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo == null ? null : logisticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_code
     *
     * @return the value of t_export_clearance.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_code
     *
     * @param logisticsCode the value for t_export_clearance.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_name
     *
     * @return the value of t_export_clearance.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_name
     *
     * @param logisticsName the value for t_export_clearance.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_app_status
     *
     * @return the value of t_export_clearance.logistics_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsAppStatus() {
        return logisticsAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_app_status
     *
     * @param logisticsAppStatus the value for t_export_clearance.logistics_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsAppStatus(String logisticsAppStatus) {
        this.logisticsAppStatus = logisticsAppStatus == null ? null : logisticsAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_app_time
     *
     * @return the value of t_export_clearance.logistics_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getLogisticsAppTime() {
        return logisticsAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_app_time
     *
     * @param logisticsAppTime the value for t_export_clearance.logistics_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsAppTime(Date logisticsAppTime) {
        this.logisticsAppTime = logisticsAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_return_status
     *
     * @return the value of t_export_clearance.logistics_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsReturnStatus() {
        return logisticsReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_return_status
     *
     * @param logisticsReturnStatus the value for t_export_clearance.logistics_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsReturnStatus(String logisticsReturnStatus) {
        this.logisticsReturnStatus = logisticsReturnStatus == null ? null : logisticsReturnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.logistics_status
     *
     * @return the value of t_export_clearance.logistics_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsStatus() {
        return logisticsStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.logistics_status
     *
     * @param logisticsStatus the value for t_export_clearance.logistics_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsStatus(String logisticsStatus) {
        this.logisticsStatus = logisticsStatus == null ? null : logisticsStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.receipt_status
     *
     * @return the value of t_export_clearance.receipt_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReceiptStatus() {
        return receiptStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.receipt_status
     *
     * @param receiptStatus the value for t_export_clearance.receipt_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReceiptStatus(String receiptStatus) {
        this.receiptStatus = receiptStatus == null ? null : receiptStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.delivery_status
     *
     * @return the value of t_export_clearance.delivery_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getDeliveryStatus() {
        return deliveryStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.delivery_status
     *
     * @param deliveryStatus the value for t_export_clearance.delivery_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setDeliveryStatus(String deliveryStatus) {
        this.deliveryStatus = deliveryStatus == null ? null : deliveryStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.entry_stowage_status
     *
     * @return the value of t_export_clearance.entry_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEntryStowageStatus() {
        return entryStowageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.entry_stowage_status
     *
     * @param entryStowageStatus the value for t_export_clearance.entry_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEntryStowageStatus(String entryStowageStatus) {
        this.entryStowageStatus = entryStowageStatus == null ? null : entryStowageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.out_stowage_status
     *
     * @return the value of t_export_clearance.out_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOutStowageStatus() {
        return outStowageStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.out_stowage_status
     *
     * @param outStowageStatus the value for t_export_clearance.out_stowage_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOutStowageStatus(String outStowageStatus) {
        this.outStowageStatus = outStowageStatus == null ? null : outStowageStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.check_pass_status
     *
     * @return the value of t_export_clearance.check_pass_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCheckPassStatus() {
        return checkPassStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.check_pass_status
     *
     * @param checkPassStatus the value for t_export_clearance.check_pass_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCheckPassStatus(String checkPassStatus) {
        this.checkPassStatus = checkPassStatus == null ? null : checkPassStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.arrived_app_time
     *
     * @return the value of t_export_clearance.arrived_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getArrivedAppTime() {
        return arrivedAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.arrived_app_time
     *
     * @param arrivedAppTime the value for t_export_clearance.arrived_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setArrivedAppTime(Date arrivedAppTime) {
        this.arrivedAppTime = arrivedAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.leave_app_time
     *
     * @return the value of t_export_clearance.leave_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getLeaveAppTime() {
        return leaveAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.leave_app_time
     *
     * @param leaveAppTime the value for t_export_clearance.leave_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLeaveAppTime(Date leaveAppTime) {
        this.leaveAppTime = leaveAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.leave_app_status
     *
     * @return the value of t_export_clearance.leave_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLeaveAppStatus() {
        return leaveAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.leave_app_status
     *
     * @param leaveAppStatus the value for t_export_clearance.leave_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLeaveAppStatus(String leaveAppStatus) {
        this.leaveAppStatus = leaveAppStatus == null ? null : leaveAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.arrived_app_status
     *
     * @return the value of t_export_clearance.arrived_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getArrivedAppStatus() {
        return arrivedAppStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.arrived_app_status
     *
     * @param arrivedAppStatus the value for t_export_clearance.arrived_app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setArrivedAppStatus(String arrivedAppStatus) {
        this.arrivedAppStatus = arrivedAppStatus == null ? null : arrivedAppStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.overtime_flag
     *
     * @return the value of t_export_clearance.overtime_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOvertimeFlag() {
        return overtimeFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.overtime_flag
     *
     * @param overtimeFlag the value for t_export_clearance.overtime_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOvertimeFlag(String overtimeFlag) {
        this.overtimeFlag = overtimeFlag == null ? null : overtimeFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.refund_flag
     *
     * @return the value of t_export_clearance.refund_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getRefundFlag() {
        return refundFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.refund_flag
     *
     * @param refundFlag the value for t_export_clearance.refund_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setRefundFlag(String refundFlag) {
        this.refundFlag = refundFlag == null ? null : refundFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.created_by_company
     *
     * @return the value of t_export_clearance.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCreatedByCompany() {
        return createdByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.created_by_company
     *
     * @param createdByCompany the value for t_export_clearance.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCreatedByCompany(String createdByCompany) {
        this.createdByCompany = createdByCompany == null ? null : createdByCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.log_flag
     *
     * @return the value of t_export_clearance.log_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogFlag() {
        return logFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.log_flag
     *
     * @param logFlag the value for t_export_clearance.log_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogFlag(String logFlag) {
        this.logFlag = logFlag == null ? null : logFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_clearance.enterprise_id
     *
     * @return the value of t_export_clearance.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_clearance.enterprise_id
     *
     * @param enterpriseId the value for t_export_clearance.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", clearanceNo=").append(clearanceNo);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", orderType=").append(orderType);
        sb.append(", ebcCode=").append(ebcCode);
        sb.append(", ebcName=").append(ebcName);
        sb.append(", ebpCode=").append(ebpCode);
        sb.append(", ebpName=").append(ebpName);
        sb.append(", orderAppTime=").append(orderAppTime);
        sb.append(", orderAppStatus=").append(orderAppStatus);
        sb.append(", orderReturnStatus=").append(orderReturnStatus);
        sb.append(", orderCreateDate=").append(orderCreateDate);
        sb.append(", invtAppTime=").append(invtAppTime);
        sb.append(", invtAppStatus=").append(invtAppStatus);
        sb.append(", invtNo=").append(invtNo);
        sb.append(", invtCreateFlag=").append(invtCreateFlag);
        sb.append(", invtCreateDate=").append(invtCreateDate);
        sb.append(", payNo=").append(payNo);
        sb.append(", payCode=").append(payCode);
        sb.append(", payName=").append(payName);
        sb.append(", payAppTime=").append(payAppTime);
        sb.append(", payAppStatus=").append(payAppStatus);
        sb.append(", payReturnStatus=").append(payReturnStatus);
        sb.append(", logisticsNo=").append(logisticsNo);
        sb.append(", logisticsCode=").append(logisticsCode);
        sb.append(", logisticsName=").append(logisticsName);
        sb.append(", logisticsAppStatus=").append(logisticsAppStatus);
        sb.append(", logisticsAppTime=").append(logisticsAppTime);
        sb.append(", logisticsReturnStatus=").append(logisticsReturnStatus);
        sb.append(", logisticsStatus=").append(logisticsStatus);
        sb.append(", receiptStatus=").append(receiptStatus);
        sb.append(", deliveryStatus=").append(deliveryStatus);
        sb.append(", entryStowageStatus=").append(entryStowageStatus);
        sb.append(", outStowageStatus=").append(outStowageStatus);
        sb.append(", checkPassStatus=").append(checkPassStatus);
        sb.append(", arrivedAppTime=").append(arrivedAppTime);
        sb.append(", leaveAppTime=").append(leaveAppTime);
        sb.append(", leaveAppStatus=").append(leaveAppStatus);
        sb.append(", arrivedAppStatus=").append(arrivedAppStatus);
        sb.append(", overtimeFlag=").append(overtimeFlag);
        sb.append(", refundFlag=").append(refundFlag);
        sb.append(", createdByCompany=").append(createdByCompany);
        sb.append(", logFlag=").append(logFlag);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append("]");
        return sb.toString();
    }
}