package org.louis.hometutor.domain;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

public class IInventory implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String guid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.customs_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String customsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.app_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String appType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date appTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String appStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.app_uid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String appUid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.app_uname
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String appUname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.cop_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String copNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.pre_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String preNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String orderType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebpCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebpName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebcCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ebcName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String logisticsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String invtNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ie_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ieFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.port_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String portCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ie_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date ieDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.owner_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ownerCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.owner_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ownerName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.trade_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String tradeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.trade_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String tradeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.agent_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String agentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.agent_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String agentName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.trade_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String tradeMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.traf_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String trafMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.traf_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String trafName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.voyage_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String voyageNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.bill_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String billNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.loct_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String loctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.license_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String licenseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.country
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.destination_port
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String destinationPort;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.freight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private BigDecimal freight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.freight_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String freightCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.freight_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String freightMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.insured_fee
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private BigDecimal insuredFee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.insured_fee_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String insuredFeeCurr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.insured_fee_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String insuredFeeMark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.wrap_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String wrapType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.pack_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Integer packNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private BigDecimal weight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.net_weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private BigDecimal netWeight;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.note
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String note;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date returnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String returnGuid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.created_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date createdDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String createdByCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String clearanceNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Integer enterpriseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date ciqAppTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ciqFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ciqReturnStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ciqReturnInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Date ciqReturnTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_inventory.ciq_return_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String ciqReturnName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.guid
     *
     * @return the value of t_export_inventory.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getGuid() {
        return guid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.guid
     *
     * @param guid the value for t_export_inventory.guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setGuid(String guid) {
        this.guid = guid == null ? null : guid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.customs_code
     *
     * @return the value of t_export_inventory.customs_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCustomsCode() {
        return customsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.customs_code
     *
     * @param customsCode the value for t_export_inventory.customs_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCustomsCode(String customsCode) {
        this.customsCode = customsCode == null ? null : customsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.app_type
     *
     * @return the value of t_export_inventory.app_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAppType() {
        return appType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.app_type
     *
     * @param appType the value for t_export_inventory.app_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAppType(String appType) {
        this.appType = appType == null ? null : appType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.app_time
     *
     * @return the value of t_export_inventory.app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getAppTime() {
        return appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.app_time
     *
     * @param appTime the value for t_export_inventory.app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAppTime(Date appTime) {
        this.appTime = appTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.app_status
     *
     * @return the value of t_export_inventory.app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAppStatus() {
        return appStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.app_status
     *
     * @param appStatus the value for t_export_inventory.app_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAppStatus(String appStatus) {
        this.appStatus = appStatus == null ? null : appStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.app_uid
     *
     * @return the value of t_export_inventory.app_uid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAppUid() {
        return appUid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.app_uid
     *
     * @param appUid the value for t_export_inventory.app_uid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAppUid(String appUid) {
        this.appUid = appUid == null ? null : appUid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.app_uname
     *
     * @return the value of t_export_inventory.app_uname
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAppUname() {
        return appUname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.app_uname
     *
     * @param appUname the value for t_export_inventory.app_uname
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAppUname(String appUname) {
        this.appUname = appUname == null ? null : appUname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.cop_no
     *
     * @return the value of t_export_inventory.cop_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCopNo() {
        return copNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.cop_no
     *
     * @param copNo the value for t_export_inventory.cop_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCopNo(String copNo) {
        this.copNo = copNo == null ? null : copNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.pre_no
     *
     * @return the value of t_export_inventory.pre_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPreNo() {
        return preNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.pre_no
     *
     * @param preNo the value for t_export_inventory.pre_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPreNo(String preNo) {
        this.preNo = preNo == null ? null : preNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.order_no
     *
     * @return the value of t_export_inventory.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.order_no
     *
     * @param orderNo the value for t_export_inventory.order_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo == null ? null : orderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.order_type
     *
     * @return the value of t_export_inventory.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.order_type
     *
     * @param orderType the value for t_export_inventory.order_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType == null ? null : orderType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ebp_code
     *
     * @return the value of t_export_inventory.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbpCode() {
        return ebpCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ebp_code
     *
     * @param ebpCode the value for t_export_inventory.ebp_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbpCode(String ebpCode) {
        this.ebpCode = ebpCode == null ? null : ebpCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ebp_name
     *
     * @return the value of t_export_inventory.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbpName() {
        return ebpName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ebp_name
     *
     * @param ebpName the value for t_export_inventory.ebp_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbpName(String ebpName) {
        this.ebpName = ebpName == null ? null : ebpName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ebc_code
     *
     * @return the value of t_export_inventory.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbcCode() {
        return ebcCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ebc_code
     *
     * @param ebcCode the value for t_export_inventory.ebc_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbcCode(String ebcCode) {
        this.ebcCode = ebcCode == null ? null : ebcCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ebc_name
     *
     * @return the value of t_export_inventory.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getEbcName() {
        return ebcName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ebc_name
     *
     * @param ebcName the value for t_export_inventory.ebc_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEbcName(String ebcName) {
        this.ebcName = ebcName == null ? null : ebcName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.logistics_no
     *
     * @return the value of t_export_inventory.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsNo() {
        return logisticsNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.logistics_no
     *
     * @param logisticsNo the value for t_export_inventory.logistics_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsNo(String logisticsNo) {
        this.logisticsNo = logisticsNo == null ? null : logisticsNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.logistics_code
     *
     * @return the value of t_export_inventory.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsCode() {
        return logisticsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.logistics_code
     *
     * @param logisticsCode the value for t_export_inventory.logistics_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsCode(String logisticsCode) {
        this.logisticsCode = logisticsCode == null ? null : logisticsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.logistics_name
     *
     * @return the value of t_export_inventory.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLogisticsName() {
        return logisticsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.logistics_name
     *
     * @param logisticsName the value for t_export_inventory.logistics_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLogisticsName(String logisticsName) {
        this.logisticsName = logisticsName == null ? null : logisticsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.invt_no
     *
     * @return the value of t_export_inventory.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInvtNo() {
        return invtNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.invt_no
     *
     * @param invtNo the value for t_export_inventory.invt_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInvtNo(String invtNo) {
        this.invtNo = invtNo == null ? null : invtNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ie_flag
     *
     * @return the value of t_export_inventory.ie_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getIeFlag() {
        return ieFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ie_flag
     *
     * @param ieFlag the value for t_export_inventory.ie_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setIeFlag(String ieFlag) {
        this.ieFlag = ieFlag == null ? null : ieFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.port_code
     *
     * @return the value of t_export_inventory.port_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getPortCode() {
        return portCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.port_code
     *
     * @param portCode the value for t_export_inventory.port_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPortCode(String portCode) {
        this.portCode = portCode == null ? null : portCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ie_date
     *
     * @return the value of t_export_inventory.ie_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getIeDate() {
        return ieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ie_date
     *
     * @param ieDate the value for t_export_inventory.ie_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setIeDate(Date ieDate) {
        this.ieDate = ieDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.owner_code
     *
     * @return the value of t_export_inventory.owner_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOwnerCode() {
        return ownerCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.owner_code
     *
     * @param ownerCode the value for t_export_inventory.owner_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOwnerCode(String ownerCode) {
        this.ownerCode = ownerCode == null ? null : ownerCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.owner_name
     *
     * @return the value of t_export_inventory.owner_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.owner_name
     *
     * @param ownerName the value for t_export_inventory.owner_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.trade_code
     *
     * @return the value of t_export_inventory.trade_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getTradeCode() {
        return tradeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.trade_code
     *
     * @param tradeCode the value for t_export_inventory.trade_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setTradeCode(String tradeCode) {
        this.tradeCode = tradeCode == null ? null : tradeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.trade_name
     *
     * @return the value of t_export_inventory.trade_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getTradeName() {
        return tradeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.trade_name
     *
     * @param tradeName the value for t_export_inventory.trade_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setTradeName(String tradeName) {
        this.tradeName = tradeName == null ? null : tradeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.agent_code
     *
     * @return the value of t_export_inventory.agent_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAgentCode() {
        return agentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.agent_code
     *
     * @param agentCode the value for t_export_inventory.agent_code
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAgentCode(String agentCode) {
        this.agentCode = agentCode == null ? null : agentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.agent_name
     *
     * @return the value of t_export_inventory.agent_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getAgentName() {
        return agentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.agent_name
     *
     * @param agentName the value for t_export_inventory.agent_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setAgentName(String agentName) {
        this.agentName = agentName == null ? null : agentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.trade_mode
     *
     * @return the value of t_export_inventory.trade_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getTradeMode() {
        return tradeMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.trade_mode
     *
     * @param tradeMode the value for t_export_inventory.trade_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setTradeMode(String tradeMode) {
        this.tradeMode = tradeMode == null ? null : tradeMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.traf_mode
     *
     * @return the value of t_export_inventory.traf_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getTrafMode() {
        return trafMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.traf_mode
     *
     * @param trafMode the value for t_export_inventory.traf_mode
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setTrafMode(String trafMode) {
        this.trafMode = trafMode == null ? null : trafMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.traf_name
     *
     * @return the value of t_export_inventory.traf_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getTrafName() {
        return trafName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.traf_name
     *
     * @param trafName the value for t_export_inventory.traf_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setTrafName(String trafName) {
        this.trafName = trafName == null ? null : trafName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.voyage_no
     *
     * @return the value of t_export_inventory.voyage_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getVoyageNo() {
        return voyageNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.voyage_no
     *
     * @param voyageNo the value for t_export_inventory.voyage_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setVoyageNo(String voyageNo) {
        this.voyageNo = voyageNo == null ? null : voyageNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.bill_no
     *
     * @return the value of t_export_inventory.bill_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getBillNo() {
        return billNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.bill_no
     *
     * @param billNo the value for t_export_inventory.bill_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setBillNo(String billNo) {
        this.billNo = billNo == null ? null : billNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.loct_no
     *
     * @return the value of t_export_inventory.loct_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLoctNo() {
        return loctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.loct_no
     *
     * @param loctNo the value for t_export_inventory.loct_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLoctNo(String loctNo) {
        this.loctNo = loctNo == null ? null : loctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.license_no
     *
     * @return the value of t_export_inventory.license_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getLicenseNo() {
        return licenseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.license_no
     *
     * @param licenseNo the value for t_export_inventory.license_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setLicenseNo(String licenseNo) {
        this.licenseNo = licenseNo == null ? null : licenseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.country
     *
     * @return the value of t_export_inventory.country
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.country
     *
     * @param country the value for t_export_inventory.country
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.destination_port
     *
     * @return the value of t_export_inventory.destination_port
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getDestinationPort() {
        return destinationPort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.destination_port
     *
     * @param destinationPort the value for t_export_inventory.destination_port
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setDestinationPort(String destinationPort) {
        this.destinationPort = destinationPort == null ? null : destinationPort.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.freight
     *
     * @return the value of t_export_inventory.freight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public BigDecimal getFreight() {
        return freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.freight
     *
     * @param freight the value for t_export_inventory.freight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setFreight(BigDecimal freight) {
        this.freight = freight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.freight_curr
     *
     * @return the value of t_export_inventory.freight_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getFreightCurr() {
        return freightCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.freight_curr
     *
     * @param freightCurr the value for t_export_inventory.freight_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setFreightCurr(String freightCurr) {
        this.freightCurr = freightCurr == null ? null : freightCurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.freight_mark
     *
     * @return the value of t_export_inventory.freight_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getFreightMark() {
        return freightMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.freight_mark
     *
     * @param freightMark the value for t_export_inventory.freight_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setFreightMark(String freightMark) {
        this.freightMark = freightMark == null ? null : freightMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.insured_fee
     *
     * @return the value of t_export_inventory.insured_fee
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public BigDecimal getInsuredFee() {
        return insuredFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.insured_fee
     *
     * @param insuredFee the value for t_export_inventory.insured_fee
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInsuredFee(BigDecimal insuredFee) {
        this.insuredFee = insuredFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.insured_fee_curr
     *
     * @return the value of t_export_inventory.insured_fee_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInsuredFeeCurr() {
        return insuredFeeCurr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.insured_fee_curr
     *
     * @param insuredFeeCurr the value for t_export_inventory.insured_fee_curr
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInsuredFeeCurr(String insuredFeeCurr) {
        this.insuredFeeCurr = insuredFeeCurr == null ? null : insuredFeeCurr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.insured_fee_mark
     *
     * @return the value of t_export_inventory.insured_fee_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getInsuredFeeMark() {
        return insuredFeeMark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.insured_fee_mark
     *
     * @param insuredFeeMark the value for t_export_inventory.insured_fee_mark
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setInsuredFeeMark(String insuredFeeMark) {
        this.insuredFeeMark = insuredFeeMark == null ? null : insuredFeeMark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.wrap_type
     *
     * @return the value of t_export_inventory.wrap_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getWrapType() {
        return wrapType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.wrap_type
     *
     * @param wrapType the value for t_export_inventory.wrap_type
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setWrapType(String wrapType) {
        this.wrapType = wrapType == null ? null : wrapType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.pack_no
     *
     * @return the value of t_export_inventory.pack_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Integer getPackNo() {
        return packNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.pack_no
     *
     * @param packNo the value for t_export_inventory.pack_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setPackNo(Integer packNo) {
        this.packNo = packNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.weight
     *
     * @return the value of t_export_inventory.weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public BigDecimal getWeight() {
        return weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.weight
     *
     * @param weight the value for t_export_inventory.weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.net_weight
     *
     * @return the value of t_export_inventory.net_weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public BigDecimal getNetWeight() {
        return netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.net_weight
     *
     * @param netWeight the value for t_export_inventory.net_weight
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setNetWeight(BigDecimal netWeight) {
        this.netWeight = netWeight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.note
     *
     * @return the value of t_export_inventory.note
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getNote() {
        return note;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.note
     *
     * @param note the value for t_export_inventory.note
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setNote(String note) {
        this.note = note == null ? null : note.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.return_status
     *
     * @return the value of t_export_inventory.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnStatus() {
        return returnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.return_status
     *
     * @param returnStatus the value for t_export_inventory.return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnStatus(String returnStatus) {
        this.returnStatus = returnStatus == null ? null : returnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.return_time
     *
     * @return the value of t_export_inventory.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getReturnTime() {
        return returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.return_time
     *
     * @param returnTime the value for t_export_inventory.return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnTime(Date returnTime) {
        this.returnTime = returnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.return_info
     *
     * @return the value of t_export_inventory.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnInfo() {
        return returnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.return_info
     *
     * @param returnInfo the value for t_export_inventory.return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnInfo(String returnInfo) {
        this.returnInfo = returnInfo == null ? null : returnInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.return_guid
     *
     * @return the value of t_export_inventory.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getReturnGuid() {
        return returnGuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.return_guid
     *
     * @param returnGuid the value for t_export_inventory.return_guid
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setReturnGuid(String returnGuid) {
        this.returnGuid = returnGuid == null ? null : returnGuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.created_date
     *
     * @return the value of t_export_inventory.created_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getCreatedDate() {
        return createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.created_date
     *
     * @param createdDate the value for t_export_inventory.created_date
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCreatedDate(Date createdDate) {
        this.createdDate = createdDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.created_by_company
     *
     * @return the value of t_export_inventory.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCreatedByCompany() {
        return createdByCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.created_by_company
     *
     * @param createdByCompany the value for t_export_inventory.created_by_company
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCreatedByCompany(String createdByCompany) {
        this.createdByCompany = createdByCompany == null ? null : createdByCompany.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.clearance_no
     *
     * @return the value of t_export_inventory.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getClearanceNo() {
        return clearanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.clearance_no
     *
     * @param clearanceNo the value for t_export_inventory.clearance_no
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setClearanceNo(String clearanceNo) {
        this.clearanceNo = clearanceNo == null ? null : clearanceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.enterprise_id
     *
     * @return the value of t_export_inventory.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Integer getEnterpriseId() {
        return enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.enterprise_id
     *
     * @param enterpriseId the value for t_export_inventory.enterprise_id
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setEnterpriseId(Integer enterpriseId) {
        this.enterpriseId = enterpriseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_app_time
     *
     * @return the value of t_export_inventory.ciq_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getCiqAppTime() {
        return ciqAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_app_time
     *
     * @param ciqAppTime the value for t_export_inventory.ciq_app_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqAppTime(Date ciqAppTime) {
        this.ciqAppTime = ciqAppTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_flag
     *
     * @return the value of t_export_inventory.ciq_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCiqFlag() {
        return ciqFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_flag
     *
     * @param ciqFlag the value for t_export_inventory.ciq_flag
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqFlag(String ciqFlag) {
        this.ciqFlag = ciqFlag == null ? null : ciqFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_return_status
     *
     * @return the value of t_export_inventory.ciq_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCiqReturnStatus() {
        return ciqReturnStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_return_status
     *
     * @param ciqReturnStatus the value for t_export_inventory.ciq_return_status
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqReturnStatus(String ciqReturnStatus) {
        this.ciqReturnStatus = ciqReturnStatus == null ? null : ciqReturnStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_return_info
     *
     * @return the value of t_export_inventory.ciq_return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCiqReturnInfo() {
        return ciqReturnInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_return_info
     *
     * @param ciqReturnInfo the value for t_export_inventory.ciq_return_info
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqReturnInfo(String ciqReturnInfo) {
        this.ciqReturnInfo = ciqReturnInfo == null ? null : ciqReturnInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_return_time
     *
     * @return the value of t_export_inventory.ciq_return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Date getCiqReturnTime() {
        return ciqReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_return_time
     *
     * @param ciqReturnTime the value for t_export_inventory.ciq_return_time
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqReturnTime(Date ciqReturnTime) {
        this.ciqReturnTime = ciqReturnTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_inventory.ciq_return_name
     *
     * @return the value of t_export_inventory.ciq_return_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getCiqReturnName() {
        return ciqReturnName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_inventory.ciq_return_name
     *
     * @param ciqReturnName the value for t_export_inventory.ciq_return_name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCiqReturnName(String ciqReturnName) {
        this.ciqReturnName = ciqReturnName == null ? null : ciqReturnName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", guid=").append(guid);
        sb.append(", customsCode=").append(customsCode);
        sb.append(", appType=").append(appType);
        sb.append(", appTime=").append(appTime);
        sb.append(", appStatus=").append(appStatus);
        sb.append(", appUid=").append(appUid);
        sb.append(", appUname=").append(appUname);
        sb.append(", copNo=").append(copNo);
        sb.append(", preNo=").append(preNo);
        sb.append(", orderNo=").append(orderNo);
        sb.append(", orderType=").append(orderType);
        sb.append(", ebpCode=").append(ebpCode);
        sb.append(", ebpName=").append(ebpName);
        sb.append(", ebcCode=").append(ebcCode);
        sb.append(", ebcName=").append(ebcName);
        sb.append(", logisticsNo=").append(logisticsNo);
        sb.append(", logisticsCode=").append(logisticsCode);
        sb.append(", logisticsName=").append(logisticsName);
        sb.append(", invtNo=").append(invtNo);
        sb.append(", ieFlag=").append(ieFlag);
        sb.append(", portCode=").append(portCode);
        sb.append(", ieDate=").append(ieDate);
        sb.append(", ownerCode=").append(ownerCode);
        sb.append(", ownerName=").append(ownerName);
        sb.append(", tradeCode=").append(tradeCode);
        sb.append(", tradeName=").append(tradeName);
        sb.append(", agentCode=").append(agentCode);
        sb.append(", agentName=").append(agentName);
        sb.append(", tradeMode=").append(tradeMode);
        sb.append(", trafMode=").append(trafMode);
        sb.append(", trafName=").append(trafName);
        sb.append(", voyageNo=").append(voyageNo);
        sb.append(", billNo=").append(billNo);
        sb.append(", loctNo=").append(loctNo);
        sb.append(", licenseNo=").append(licenseNo);
        sb.append(", country=").append(country);
        sb.append(", destinationPort=").append(destinationPort);
        sb.append(", freight=").append(freight);
        sb.append(", freightCurr=").append(freightCurr);
        sb.append(", freightMark=").append(freightMark);
        sb.append(", insuredFee=").append(insuredFee);
        sb.append(", insuredFeeCurr=").append(insuredFeeCurr);
        sb.append(", insuredFeeMark=").append(insuredFeeMark);
        sb.append(", wrapType=").append(wrapType);
        sb.append(", packNo=").append(packNo);
        sb.append(", weight=").append(weight);
        sb.append(", netWeight=").append(netWeight);
        sb.append(", note=").append(note);
        sb.append(", returnStatus=").append(returnStatus);
        sb.append(", returnTime=").append(returnTime);
        sb.append(", returnInfo=").append(returnInfo);
        sb.append(", returnGuid=").append(returnGuid);
        sb.append(", createdDate=").append(createdDate);
        sb.append(", createdByCompany=").append(createdByCompany);
        sb.append(", clearanceNo=").append(clearanceNo);
        sb.append(", enterpriseId=").append(enterpriseId);
        sb.append(", ciqAppTime=").append(ciqAppTime);
        sb.append(", ciqFlag=").append(ciqFlag);
        sb.append(", ciqReturnStatus=").append(ciqReturnStatus);
        sb.append(", ciqReturnInfo=").append(ciqReturnInfo);
        sb.append(", ciqReturnTime=").append(ciqReturnTime);
        sb.append(", ciqReturnName=").append(ciqReturnName);
        sb.append("]");
        return sb.toString();
    }
}