package org.louis.hometutor.domain;

import java.io.Serializable;

public class Sequence implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_sequence.name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_sequence.current_value
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Long currentValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_export_sequence.increment
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private Long increment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_sequence.name
     *
     * @return the value of t_export_sequence.name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_sequence.name
     *
     * @param name the value for t_export_sequence.name
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_sequence.current_value
     *
     * @return the value of t_export_sequence.current_value
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Long getCurrentValue() {
        return currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_sequence.current_value
     *
     * @param currentValue the value for t_export_sequence.current_value
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setCurrentValue(Long currentValue) {
        this.currentValue = currentValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_export_sequence.increment
     *
     * @return the value of t_export_sequence.increment
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public Long getIncrement() {
        return increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_export_sequence.increment
     *
     * @param increment the value for t_export_sequence.increment
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    public void setIncrement(Long increment) {
        this.increment = increment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", name=").append(name);
        sb.append(", currentValue=").append(currentValue);
        sb.append(", increment=").append(increment);
        sb.append("]");
        return sb.toString();
    }
}