package com.foo.tourist.dao;

import org.louis.hometutor.domain.BaseReturn;

public interface BaseReturnMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insert(BaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insertSelective(BaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    BaseReturn selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKeySelective(BaseReturn record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_base_return
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKey(BaseReturn record);
}