package com.foo.tourist.dao;

import org.louis.hometutor.domain.Clearance;

public interface ClearanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int deleteByPrimaryKey(String clearanceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insert(Clearance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insertSelective(Clearance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    Clearance selectByPrimaryKey(String clearanceNo);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKeySelective(Clearance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_clearance
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKey(Clearance record);
}