package com.foo.tourist.dao;

import org.louis.hometutor.domain.IInventory;

public interface IInventoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insert(IInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insertSelective(IInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    IInventory selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKeySelective(IInventory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKey(IInventory record);
}