package com.foo.tourist.dao;

import org.louis.hometutor.domain.IInventoryList;

public interface IInventoryListMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int deleteByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insert(IInventoryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insertSelective(IInventoryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    IInventoryList selectByPrimaryKey(String guid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKeySelective(IInventoryList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_inventory_list
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKey(IInventoryList record);
}