package com.foo.tourist.dao;

import org.louis.hometutor.domain.Sequence;

public interface SequenceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int deleteByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insert(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int insertSelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    Sequence selectByPrimaryKey(String name);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKeySelective(Sequence record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_export_sequence
     *
     * @mbggenerated Mon Jan 15 11:52:07 CST 2018
     */
    int updateByPrimaryKey(Sequence record);
}